version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app           
      - /app/node_modules        
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    command: ["npm", "run", "dev"]  

  frontend:
    build:
      context: ./frontend/Quiz-App
      dockerfile: Dockerfile
    volumes:
      - ./frontend/Quiz-App/src:/app/src  
      - ./frontend/Quiz-App/public:/app/public
      - /app/node_modules         
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
