export const quotes = [
  "If you can’t be kind, at least be vague. — Judith Martin",
  "There is no such thing as fun for the whole family. — Jerry Seinfeld",
  "Always forgive your enemies; nothing annoys them so much. — Oscar Wilde",
  "Instant gratification takes too long. — Carrie Fisher",
  "Accept who you are. Unless you’re a serial killer. — Ellen DeGeneres",
  "All you need is love. But a little chocolate now and then doesn’t hurt. — Charles M. Schulz",
  "When I was a kid my parents moved a lot, but I always found them. — Rodney Dangerfield",
  "I generally avoid temptation unless I can’t resist it. — Mae West",
  "Love is blind but marriage is a real eye-opener. — Pauline Thomason",
  "Age is something that doesn’t matter, unless you are a cheese. — Luis Buñuel",
  "A day without sunshine is like, you know, night. — Steve Martin",
  "The secret of staying young is to live honestly, eat slowly, and lie about your age. — Lucille Ball",
  "Just keep swimming. — Finding Nemo",
  "Well, nobody’s perfect. — Some Like It Hot",
  "You only live once, but if you do it right, once is enough. — Mae West",
  "Life is what happens when you’re busy making other plans. — John Lennon",
  "Get busy living or get busy dying. — Stephen King",
  "You miss 100% of the shots you don’t take. — Wayne Gretzky",
  "The best way to predict the future is to invent it. — Alan Kay",
  "Do one thing every day that scares you. — Eleanor Roosevelt",
  "The only impossible journey is the one you never begin. — Tony Robbins",
  "Life is 10% what happens to us and 90% how we react to it. — Charles R. Swindoll",
  "In three words I can sum up everything I've learned about life: it goes on. — Robert Frost",
  "To live is to suffer, to survive is to find some meaning in the suffering. — Friedrich Nietzsche",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate. — Ralph Waldo Emerson",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. — Brian Tracy",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Success is not the key to happiness. Happiness is the key to success. — Albert Schweitzer",
  "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
  "Don’t watch the clock; do what it does. Keep going. — Sam Levenson",
  "Keep your face always toward the sunshine—and shadows will fall behind you. — Walt Whitman",
  "It does not matter how slowly you go as long as you do not stop. — Confucius",
  "Everything you can imagine is real. — Pablo Picasso",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
  "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
  "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
  "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
  "It always seems impossible until it's done. — Nelson Mandela",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "Happiness is not something ready-made. It comes from your own actions. — Dalai Lama",
  "Dream big and dare to fail. — Norman Vaughan",
  "Turn your wounds into wisdom. — Oprah Winfrey",
  "Don’t count the days, make the days count. — Muhammad Ali",
  "Keep your eyes on the stars, and your feet on the ground. — Theodore Roosevelt",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. — Zig Ziglar",
  "The harder I work, the luckier I get. — Samuel Goldwyn",
  "Do not take life too seriously. You will never get out of it alive. — Elbert Hubbard",
  "I find that the harder I work, the more luck I seem to have. — Thomas Jefferson",
  "Courage is not the absence of fear — it’s inspiring others to move beyond it. — Nelson Mandela",
  "Strive not to be a success, but rather to be of value. — Albert Einstein",
  "Opportunities don’t happen. You create them. — Chris Grosser",
  "Don’t be afraid to give up the good to go for the great. — John D. Rockefeller",
  "I attribute my success to this: I never gave or took any excuse. — Florence Nightingale",
  "You can’t cross the sea merely by standing and staring at the water. — Rabindranath Tagore",
  "Do one thing every day that scares you. — Eleanor Roosevelt",
  "If you want to achieve greatness stop asking for permission. — Anonymous",
  "If you are not willing to risk the usual you will have to settle for the ordinary. — Jim Rohn",
  "Magic is believing in yourself, if you can do that, you can make anything happen. — Johann Wolfgang von Goethe",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. — Eleanor Roosevelt",
  "All progress takes place outside the comfort zone. — Michael John Bobak",
  "The man who has confidence in himself gains the confidence of others. — Hasidic Proverb",
  "The best revenge is massive success. — Frank Sinatra",
  "Your limitation—it’s only your imagination. — Anonymous",
  "Push yourself, because no one else is going to do it for you. — Anonymous",
  "Sometimes later becomes never. Do it now. — Anonymous",
  "Great things never come from comfort zones. — Anonymous",
  "Dream it. Wish it. Do it. — Anonymous",
  "Success doesn’t just find you. You have to go out and get it. — Anonymous",
  "The harder you work for something, the greater you’ll feel when you achieve it. — Anonymous",
  "Don’t stop when you’re tired. Stop when you’re done. — Anonymous",
  "Wake up with determination. Go to bed with satisfaction. — Anonymous",
  "Do something today that your future self will thank you for. — Anonymous",
  "Little things make big days. — Anonymous",
  "It’s going to be hard, but hard does not mean impossible. — Anonymous",
  "Don’t wait for opportunity. Create it. — Anonymous",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths. — Anonymous",
  "The key to success is to focus on goals, not obstacles. — Anonymous",
  "Failure is not the opposite of success; it’s part of success. — Arianna Huffington",
  "Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill",
  "Do not let what you cannot do interfere with what you can do. — John Wooden",
  "Keep going. Everything you need will come to you at the perfect time. — Anonymous",
  "Don’t wait for the perfect moment. Take the moment and make it perfect. — Anonymous",
  "What you do today can improve all your tomorrows. — Ralph Marston",
  "Believe in yourself and all that you are. — Christian D. Larson",
  "You don’t have to be great to start, but you have to start to be great. — Zig Ziglar",
  "Act as if what you do makes a difference. It does. — William James",
  "Your life only gets better when you get better. — Brian Tracy",
  "Don’t wish it were easier. Wish you were better. — Jim Rohn",
  "Motivation is what gets you started. Habit is what keeps you going. — Jim Ryun",
  "Sometimes the smallest step in the right direction ends up being the biggest step of your life. — Naeem Callaway",
  "You are capable of amazing things. — Anonymous",
  "Little by little, a little becomes a lot. — Tanzanian Proverb",
  "Success is not in what you have, but who you are. — Bo Bennett",
  "Work hard in silence, let your success be your noise. — Frank Ocean",
  "Don’t limit your challenges. Challenge your limits. — Anonymous",
  "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change. — Anonymous",
  "Push yourself because no one else is going to do it for you. — Anonymous",
  "Sometimes later becomes never. Do it now. — Anonymous",
  "Great things never come from comfort zones. — Anonymous",
  "Dream it. Wish it. Do it. — Anonymous",
  "Success doesn’t just find you. You have to go out and get it. — Anonymous",
  "The key to success is to focus on goals, not obstacles. — Anonymous",
  "Failure is simply the opportunity to begin again, this time more intelligently. — Henry Ford",
  "It always seems impossible until it’s done. — Nelson Mandela"
]